language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'ksofe-generator' ]; then cd .. && eval "mv $currentfolder ksofe-generator" && cd ksofe-generator; fi

